/**
 * Terms of Service Page
 *
 * Comprehensive terms of service explaining:
 * - User responsibilities
 * - Usage restrictions
 * - Intellectual property
 * - Limitation of liability
 * - Dispute resolution
 * - Service level agreements
 */

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto prose prose-lg">
        <h1>Terms of Service</h1>

        <p className="text-gray-500">Last Updated: June 3, 2026</p>

        <h2>1. Agreement to Terms</h2>

        <p>
          These Terms of Service ("Terms") constitute a legally binding agreement between you
          ("User" or "you") and ViveScript Solutions ("Company," "we," "us," or "our") governing your use
          of the ViveKit web application (the "Service").
        </p>

        <p>
          By accessing and using ViveKit, you accept and agree to be bound by and comply with these Terms.
          If you do not agree with any part of these Terms, you may not use the Service.
        </p>

        <p>
          We reserve the right to modify these Terms at any time. Your continued use of the Service after
          modifications constitutes acceptance of the updated Terms. We will notify you of material changes
          via email or by posting updated Terms on our website.
        </p>

        <h2>2. Service Description</h2>

        <p>
          ViveKit is a free AI client communication toolkit that helps freelancers, agencies, and consultants
          draft responses to client conversations. The Service:
        </p>

        <ul>
          <li>Parses conversation history (email, Slack, tickets)</li>
          <li>Extracts lead and client intelligence</li>
          <li>Generates AI-powered responses respecting your business rules</li>
          <li>Integrates with CRM systems for client context</li>
          <li>Routes requests to AI providers of your choice (Gemini, OpenAI, Claude)</li>
        </ul>

        <p>
          ViveKit is provided on an "as-is" basis. We make no guarantees about uptime, response quality,
          or suitability for any particular purpose.
        </p>

        <h2>3. User Responsibilities & Restrictions</h2>

        <h3>3.1 Acceptable Use</h3>

        <p>You agree to use ViveKit only for lawful purposes and in a way that does not violate the rights of others
        or restrict their use and enjoyment of ViveKit. Prohibited behavior includes:</p>

        <ul>
          <li>Harassing or causing distress or inconvenience to any person</li>
          <li>Obscene or offensive language or behavior</li>
          <li>Disrupting the normal flow of dialogue within ViveKit</li>
          <li>Attempting to gain unauthorized access to our systems</li>
          <li>Submitting malicious code or viruses</li>
          <li>Reverse engineering or attempting to reverse engineer ViveKit</li>
          <li>Violating applicable laws or regulations</li>
          <li>Infringing on intellectual property rights of others</li>
        </ul>

        <h3>3.2 Content Responsibility</h3>

        <p>
          You are solely responsible for the content you submit to ViveKit, including conversations,
          business profiles, and CRM data. You represent and warrant that:
        </p>

        <ul>
          <li>You have the right to provide the content to ViveKit</li>
          <li>Your content does not infringe on third-party intellectual property rights</li>
          <li>Your content does not contain confidential information of others</li>
          <li>Your content complies with all applicable laws</li>
        </ul>

        <p>
          ViveKit is not responsible for content you provide, including its accuracy, legality, or appropriateness.
        </p>

        <h3>3.3 AI Response Use</h3>

        <p>
          Responses generated by ViveKit are suggestions only. You are solely responsible for:
        </p>

        <ul>
          <li>Reviewing responses before sending to clients</li>
          <li>Ensuring responses comply with your business policies and applicable laws</li>
          <li>Correcting any inaccuracies or inappropriate content</li>
          <li>Obtaining all necessary approvals before sending</li>
          <li>Honoring any commitments made in the response</li>
        </ul>

        <p>
          ViveKit provides validation tools to help catch policy violations, but validation is not guaranteed.
          Final responsibility rests with you.
        </p>

        <h2>4. Intellectual Property Rights</h2>

        <h3>4.1 Our IP</h3>

        <p>
          ViveKit, including all software, features, designs, graphics, and interfaces, is the intellectual
          property of ViveScript Solutions or our licensors. You are granted a limited, non-exclusive,
          non-transferable license to use ViveKit for personal or business purposes.
        </p>

        <p>
          You may not copy, modify, distribute, reproduce, or create derivative works of ViveKit without
          our explicit written permission.
        </p>

        <h3>4.2 Your Content</h3>

        <p>
          You retain all intellectual property rights to content you upload to ViveKit (conversations, CRM data,
          business profiles). By uploading content, you grant ViveKit:
        </p>

        <ul>
          <li>A non-exclusive license to store and process your content</li>
          <li>The right to use your content to provide and improve the Service</li>
          <li>The right to create aggregated, anonymized insights from your usage</li>
        </ul>

        <p>
          We will not sell or share your content with third parties without your consent.
        </p>

        <h3>4.3 AI Provider IP</h3>

        <p>
          Responses generated by AI providers (Gemini, OpenAI, Claude) are subject to their respective
          terms and licenses. Please refer to their documentation for IP rights regarding generated content.
        </p>

        <h2>5. Disclaimers & Limitation of Liability</h2>

        <h3>5.1 AS-IS Service</h3>

        <p>
          ViveKit is provided on an "AS-IS" and "AS-AVAILABLE" basis. We make no warranties, express or implied,
          about the Service, including:
        </p>

        <ul>
          <li>Merchantability or fitness for a particular purpose</li>
          <li>Accuracy, completeness, or reliability of content</li>
          <li>Uninterrupted or error-free operation</li>
          <li>Security or freedom from viruses</li>
        </ul>

        <h3>5.2 No Liability for Generated Content</h3>

        <p>
          ViveKit does not guarantee the quality, accuracy, or legality of AI-generated responses. You are
          solely responsible for reviewing and approving all content before sending. ViveKit will not be liable
          for:
        </p>

        <ul>
          <li>Inaccurate or inappropriate AI-generated responses</li>
          <li>Responses that violate applicable laws</li>
          <li>Client dissatisfaction with responses</li>
          <li>Business losses resulting from responses</li>
        </ul>

        <h3>5.3 Limitation of Damages</h3>

        <p>
          In no event shall ViveKit, its officers, directors, employees, or agents be liable for any direct,
          indirect, incidental, special, consequential, or punitive damages arising from your use of the Service,
          including:
        </p>

        <ul>
          <li>Lost profits or revenue</li>
          <li>Lost client relationships</li>
          <li>Data loss or corruption</li>
          <li>Business interruption</li>
          <li>Any other damages</li>
        </ul>

        <p>
          This limitation applies even if we have been advised of the possibility of such damages.
        </p>

        <h3>5.4 Liability Cap</h3>

        <p>
          Our total liability to you for any claims arising from these Terms or your use of ViveKit shall not
          exceed the total amount you have paid for ViveKit in the 12 months prior to the claim.
          If you have not paid anything, our liability is limited to $100.
        </p>

        <h2>6. Third-Party Services & Links</h2>

        <h3>6.1 AI Providers</h3>

        <p>
          ViveKit integrates with third-party AI providers (Google Gemini, OpenAI, Anthropic Claude).
          When you generate responses, your content is transmitted to these providers. You are responsible for:
        </p>

        <ul>
          <li>Providing valid API keys</li>
          <li>Complying with each provider's terms of service</li>
          <li>Ensuring your content complies with each provider's usage policies</li>
          <li>Understanding their privacy policies and data handling practices</li>
        </ul>

        <p>
          ViveKit is not responsible for third-party services or their actions. Refer to their terms:
        </p>

        <ul>
          <li>Google Gemini: <a href="https://ai.google.dev/terms">https://ai.google.dev/terms</a></li>
          <li>OpenAI: <a href="https://openai.com/policies/terms-of-use">https://openai.com/policies/terms-of-use</a></li>
          <li>Anthropic: <a href="https://www.anthropic.com/terms">https://www.anthropic.com/terms</a></li>
        </ul>

        <h3>6.2 External Links</h3>

        <p>
          ViveKit may contain links to external websites. We are not responsible for the content, accuracy,
          or practices of external sites. Access external sites at your own risk.
        </p>

        <h2>7. Uptime & Service Level</h2>

        <h3>7.1 Service Availability</h3>

        <p>
          While we strive to maintain 99.5% uptime, ViveKit is provided without guaranteed availability.
          We are not liable for downtime, data loss, or service interruptions caused by:
        </p>

        <ul>
          <li>Scheduled maintenance</li>
          <li>Infrastructure failures</li>
          <li>Third-party provider outages (Supabase, Vercel, cloud providers)</li>
          <li>Denial-of-service attacks</li>
          <li>Natural disasters or acts of God</li>
          <li>Force majeure events</li>
        </ul>

        <h3>7.2 Maintenance</h3>

        <p>
          We may perform scheduled maintenance with reasonable notice. During maintenance, ViveKit may be
          unavailable. We will attempt to schedule maintenance during low-usage hours.
        </p>

        <h2>8. Payment & Refunds</h2>

        <p>
          ViveKit is offered for free. No payment is required to use the Service. We may introduce paid
          features in the future. If you use paid features, the applicable pricing and refund policy
          will be provided at the time of purchase.
        </p>

        <h2>9. Account Termination</h2>

        <h3>9.1 Termination by You</h3>

        <p>
          You may terminate your ViveKit account at any time by:
        </p>

        <ol>
          <li>Logging into your account</li>
          <li>Going to Settings → Account</li>
          <li>Clicking "Delete My Account & All Data"</li>
          <li>Confirming your decision</li>
        </ol>

        <p>
          Upon termination, all your data will be permanently deleted within 24 hours.
        </p>

        <h3>9.2 Termination by ViveKit</h3>

        <p>
          We may terminate or suspend your account immediately if you:
        </p>

        <ul>
          <li>Violate these Terms of Service</li>
          <li>Engage in illegal activities</li>
          <li>Abuse the Service or attempt unauthorized access</li>
          <li>Violate third-party intellectual property rights</li>
          <li>Create risk to our systems or other users</li>
        </ul>

        <p>
          Upon termination by us, we will make reasonable efforts to notify you and allow data export if possible.
        </p>

        <h2>10. Dispute Resolution & Governing Law</h2>

        <h3>10.1 Informal Resolution</h3>

        <p>
          Before initiating legal proceedings, we encourage you to contact us to resolve disputes informally:
        </p>

        <div className="bg-gray-50 p-4 rounded">
          <p>
            ViveScript Solutions<br/>
            Legal Team<br/>
            Email: <a href="mailto:legal@vivescriptsolutions.com">legal@vivescriptsolutions.com</a>
          </p>
        </div>

        <h3>10.2 Governing Law</h3>

        <p>
          These Terms are governed by and construed in accordance with the laws of Delaware, without regard
          to its conflict of law principles. You agree to submit to the exclusive jurisdiction of Delaware courts.
        </p>

        <h3>10.3 Arbitration</h3>

        <p>
          Any legal dispute arising from these Terms or your use of ViveKit shall be resolved through binding
          arbitration in Delaware, administered by the American Arbitration Association (AAA). Each party bears
          its own costs.
        </p>

        <h2>11. General Provisions</h2>

        <h3>11.1 Entire Agreement</h3>

        <p>
          These Terms, along with our Privacy Policy, constitute the entire agreement between you and ViveScript
          Solutions regarding your use of ViveKit. They supersede all prior agreements and understandings.
        </p>

        <h3>11.2 Severability</h3>

        <p>
          If any provision of these Terms is found to be invalid or unenforceable, that provision will be
          modified to the minimum extent necessary to make it valid, or if not possible, severed. The remaining
          provisions will continue in full effect.
        </p>

        <h3>11.3 Waiver</h3>

        <p>
          Our failure to enforce any provision of these Terms does not constitute a waiver of that provision.
        </p>

        <h3>11.4 Assignment</h3>

        <p>
          You may not assign these Terms or your rights under them without our written consent. We may assign
          these Terms in connection with a merger, acquisition, or sale of assets.
        </p>

        <h2>12. Contact Information</h2>

        <p>
          For questions about these Terms of Service, please contact:
        </p>

        <div className="bg-gray-50 p-6 rounded-lg">
          <p>
            <strong>ViveScript Solutions</strong><br/>
            Legal Compliance<br/>
            Email: <a href="mailto:legal@vivescriptsolutions.com">legal@vivescriptsolutions.com</a><br/>
            Website: <a href="https://vivescriptsolutions.com">https://vivescriptsolutions.com</a>
          </p>
        </div>

        <p className="text-gray-500 text-sm mt-8">
          These Terms of Service are effective as of June 3, 2026 and were last updated on June 3, 2026.
        </p>
      </div>
    </div>
  );
}
